In [4]:
import numpy as np

def lu_decomposition(matrix):
    rows, cols = matrix.shape
    # Create matrices L and U filled with zeros
    L = np.zeros((rows, cols))
    U = np.zeros((rows, cols))

    for j in range(cols):
        # U matrix
        U[:, j] = matrix[:, j]
        for i in range(j):
            # L matrix
            L[i, j] = matrix[i, j] / U[i, i]
            U[:, j] -= L[i, j] * U[:, i]

    # Fill diagonal of L with ones
    np.fill_diagonal(L, 1)

    return L, U

# Example usage with a 6x6 matrix
A = np.array([[2, -3, 4, 5, -7, 8],
              [-2, 0, -7, 6, 1, 9],
              [4, 1, -9, 7, 8, -2],
              [6, -7, 8, -9, 1, 3],
              [-4, 3, -2, 1, 0, -1],
              [-6, -5, 4, -3, -2, 7]])

L, U = lu_decomposition(A)

print("Matrix A:")
print(A)
print("\nMatrix L:")
print(L)
print("\nMatrix U:")
print(U)


Matrix A:
[[ 2 -3  4  5 -7  8]
 [-2  0 -7  6  1  9]
 [ 4  1 -9  7  8 -2]
 [ 6 -7  8 -9  1  3]
 [-4  3 -2  1  0 -1]
 [-6 -5  4 -3 -2  7]]

Matrix L:
[[ 1.         -1.5         2.          2.5        -3.5         4.        ]
 [ 0.          1.          2.33333333 -2.         -0.33333333 -3.        ]
 [ 0.          0.          1.         -0.21       -0.24        0.06      ]
 [ 0.          0.          0.          1.         -0.04582951 -0.13748854]
 [ 0.          0.          0.          0.          1.          0.08676234]
 [ 0.          0.          0.          0.          0.          1.        ]]

Matrix U:
[[  2.           0.           0.           0.           0.
    0.        ]
 [ -2.          -3.           4.           5.84        -5.77235564
    9.06375618]
 [  4.           7.         -33.33333333   4.          16.51665139
    4.11693083]
 [  6.           2.          -8.66666667 -21.82        19.58666667
  -19.17938506]
 [ -4.          -3.          13.           7.73       -11.52573786

In [3]:
import numpy as np #8 unknowns

def lu_decomposition(matrix):
    rows, cols = matrix.shape
    # Create matrices L and U filled with zeros
    L = np.zeros((rows, cols))
    U = np.zeros((rows, cols))

    for j in range(cols):
        # U matrix
        U[:, j] = matrix[:, j]
        for i in range(j):
            # L matrix
            L[i, j] = matrix[i, j] / U[i, i]
            U[:, j] -= L[i, j] * U[:, i]

    # Fill diagonal of L with ones
    np.fill_diagonal(L, 1)

    return L, U

# Example usage with an 8x8 matrix
A = np.array([[2, -1, 1, 0, 3, 2, 1, 4],
              [3, 3, 9, 1, 5, 6, 2, 7],
              [1, 2, 2, -1, 1, 2, 3, 1],
              [5, 1, 3, 3, 6, 7, 4, 8],
              [2, 5, 5, 2, 8, 9, 6, 2],
              [4, 6, 7, 4, 11, 13, 5, 3],
              [1, 2, 3, 4, 5, 6, 7, 8],
              [4, 8, 6, 2, 1, 3, 5, 7]])

L, U = lu_decomposition(A)

print("Matrix A:")
print(A)
print("\nMatrix L:")
print(L)
print("\nMatrix U:")
print(U)


Matrix A:
[[ 2 -1  1  0  3  2  1  4]
 [ 3  3  9  1  5  6  2  7]
 [ 1  2  2 -1  1  2  3  1]
 [ 5  1  3  3  6  7  4  8]
 [ 2  5  5  2  8  9  6  2]
 [ 4  6  7  4 11 13  5  3]
 [ 1  2  3  4  5  6  7  8]
 [ 4  8  6  2  1  3  5  7]]

Matrix L:
[[ 1.         -0.5         0.5         0.          1.5         1.
   0.5         2.        ]
 [ 0.          1.          2.          0.22222222  1.11111111  1.33333333
   0.44444444  1.55555556]
 [ 0.          0.          1.          0.28571429 -0.28571429 -0.57142857
  -0.85714286 -0.28571429]
 [ 0.          0.          0.          1.          1.47081712  1.71595331
   0.98054475  1.96108949]
 [ 0.          0.          0.          0.          1.         -1.08501798
  -0.72334532 -0.24111511]
 [ 0.          0.          0.          0.          0.          1.
  -0.14992455 -0.08995473]
 [ 0.          0.          0.          0.          0.          0.
   1.         -1.09913156]
 [ 0.          0.          0.          0.          0.          0.
   0.        